Database:
  #Data source
  source: Oracle
  host: 10.32.233.209
  port: 1521
  username: empower
  passwd: empower
  service: ami_empower
  database: ami_db
  sid: ami_empower

HESAPI:
  url: http://empower.hes-api.kaifa.tst/

TaskData:
  REG_CHECK_COMM: [ { "registerId": "9300" } ]

Request:
  deviceNo: M202009040003
  correlationId: test-correlationid
  messageId: test-messageid
  createTime:
  serviceType: GET_COMMON
  businessType:
  source: MDM
  replyType:
  replyAddress:
  messageType: REQUEST
  asyncReplyFlag: false
  deviceType: METER
  retryCount: 0
  priority: 0
  startTime:
  endTime:
  transactionId: test-transactionid
  registerId: Device logical name
  registerId_Daily:
  registerId_Monthly:
  registerId_LP1:
  registerId_LP2:
  featurePoint:
  parameter: null
  jobUniqueFlag: false
  accessSelector: 1

CreateTask:
  correlationId: create_task_correlation
  messageId: create_task_message
  deviceNo: M202009040003
  deviceType:
  retryCount:
  transactionId: test-transactionid
  data:


Register:
  sql1: select register_id,class_id,attribute_id,register_desc,is_method,data_type,rw,PROTOCOL_ID from
  sql2: where device_type=1 and PTL_TYPE = (select PTL_TYPE from c_ar_model where MODEL_CODE = (select model_code from c_ar_meter where meter_no=
  sql3: ))and rw='rw' and (get_result is null or get_result like '%online%' or set_result is null or set_result like '%online%')

Profile:
  daily_len: 22
  monthly_len: 25
  lp_len:
  pq_len:
  daily_obis: Contract 1 Daily Billing
  monthly_obis: 0.0.98.1.0.255720
  lp_obis: 1.0.99.1.0.255720
  pq_obis: 1.0.99.14.0.255720
  daily_entries_obis: 1.0.99.2.0.255780
  daily_entries: 31
  daily_in_use: Contract 1 Daily Billing Entries In Use
  monthly_entries_obis: 0.0.98.1.0.255780
  monthly_entries:
  monthly_in_use: 0.0.98.1.0.255770
  lp_entries_obis: 1.0.99.1.0.255780
  lp_entries:
  lp_in_use: 1.0.99.1.0.255770
  pq_entries_obis: 1.0.99.14.0.255780
  pq_entries:
  pq_in_use: 1.0.99.14.0.255770

Core:
  ip: hes-core
  port:

FEP:
  ip:
  port:

Config:
  # object model sheet index
  object_model_sheet: 1
  # Object / Attribute Name 所在列（从0开始，即A -> 0, B -> 1, ...）
  attr_name: 1
  #attr index
  index: 0
  # Class 所在列
  class: 7
  #OBIS code / Default Value 所在列
  default_value: 10
  # set xml 所在列
  set_xml_index: 18
  # 数据类型对应列
  data_type: 19